package com.futurepath.actionbox.classification

private typealias HCase = SyntheticNotificationCorpus.Case

/**
 * A hand-authored (not scripted, not template-substituted) batch of genuinely independent
 * sentences, focused on WAITING/REPLY/ACTION per their standing as the weakest categories
 * throughout this project. Each line below was individually composed — deliberately varying
 * length (2-word fragments through run-on sentences), formality (formal/casual/slang/typos),
 * structure (statement/question/fragment), punctuation, and emoji use — rather than generated
 * by any combinatorial/substitution mechanism.
 *
 * IMPORTANT SCOPE NOTE: this is ~300 examples, not the 50,000-per-category/300,000-total
 * volume requested. That volume is not achievable as "genuinely independently written, no
 * template reuse" by any author, human or AI, in a single session — non-repeating sentence
 * structure is a finite creative resource that's exhausted long before 50,000 examples in one
 * category, and any mechanism that reaches that volume (combinatorial slots, substitution
 * pools, sampling loops) is itself a template, which is exactly what was ruled out. This file
 * is sized to what can honestly be called hand-authored. See the session report for the fuller
 * discussion, including the separate and more important point that this experiment's outcome
 * on the rule-engine validation corpus doesn't depend on data volume at all.
 */
object HandAuthoredDiversityCorpus {

    private val NAMES = SyntheticNotificationCorpus.NAMES
    private const val WHATSAPP = "com.whatsapp"
    private const val SMS = "com.google.android.apps.messaging"
    private const val GMAIL = "com.google.android.gm"

    // ---- WAITING (120 — extra weight, the weakest/data-poorest category) ----------------

    private val waitingTexts = listOf(
        "brb",
        "hold on a sec",
        "the plumber's supposed to swing by between 2 and 4, I'll text you once he's done",
        "checking",
        "Give me until Thursday, I'm still waiting on legal to sign off",
        "one moment plz",
        "lol hang on",
        "she said she'd text when she lands",
        "Still no word from the landlord but I'll bug him again tomorrow",
        "workin on it dw",
        "The technician is en route, ETA about 45 minutes",
        "gimme a sec to pull that up",
        "waiting on a callback from the insurance company, could be a while",
        "brb 2 min",
        "He's finishing up his shift, said he'd swing by after",
        "hold pls",
        "gonna need a bit more time on this one, sorry",
        "just checking with the team, one sec",
        "Should hear back from them by end of week, will let you know",
        "hmm let me look into that for u",
        "the courier says it's out but hasn't moved on the tracker in hours",
        "almost got it, promise",
        "still on hold with the bank lol",
        "he mentioned hed be free after lunch to call",
        "Waiting on the vendor to confirm inventory, should know by tomorrow morning",
        "1 sec",
        "not yet but soon",
        "My sister said shes gonna pick it up on her way home tonight",
        "yeah gimme a bit, phone's charging",
        "the doctor's office said someone would call back with the results",
        "Sitting tight until I hear from HR",
        "kk stand by",
        "she's still asleep, I'll ask when she's up",
        "waiting on my ride, should be here soon i hope",
        "Let me circle back once the numbers come in from finance",
        "hol up",
        "the repair guy is running late, said another 20 min",
        "still pending approval on my end, nothing I can do yet",
        "omw don't worry",
        "He's supposed to call once he lands, no update yet",
        "brb making coffee then I'll check",
        "the school said they'd email once attendance is finalized",
        "gonna be a bit, sorry for the wait",
        "she's typing... (for real this time)",
        "waiting for the paint to dry, literally",
        "still tracking down the invoice, bear with me",
        "yea one sec lemme grab my laptop",
        "The contractor needs to check with his supplier first, should know tomorrow",
        "sec",
        "no updates yet from the embassy, still processing apparently",
        "he said hed think about it and get back to us",
        "just putting the kids to bed, will call after",
        "still waiting to hear from the landlord about the deposit",
        "the download's at like 60%, almost there",
        "gimme til Friday, swamped rn",
        "Support ticket's still open, they said 24-48 hrs",
        "she'll be here in a few, just left",
        "waiting on wifi to reconnect, one sec",
        "I told him I'd need until next week to decide, so no rush",
        "hol on lemme ask my mom",
        "the mechanic still has it up on the lift, no verdict yet",
        "give it a minute, still loading",
        "he's got me on hold rn lol",
        "waiting to hear back from the adoption agency, fingers crossed",
        "brb, someone's at the door",
        "still no reply from him, might follow up tomorrow",
        "the cake needs another 15 min in the oven",
        "just gotta wait for my manager to sign it, shouldn't be long",
        "she's on the other line, said she'd call right after",
        "hang tight, printer's jammed again",
        "still waiting on the lab results, doc said Monday at the latest",
        "1 more min",
        "he's stuck in traffic, said maybe 20 more minutes",
        "waiting on my visa to process before we book anything",
        "the babysitter's running a few min behind",
        "gimme til tomorrow, still gathering the paperwork",
        "hes asleep rn ill tell him when he wakes up",
        "still waiting for wifi guy, he said this afternoon",
        "the review is still with legal, hoping for word by Friday",
        "sec, phone's ringing",
        "waiting on the second opinion before we decide anything",
        "she said the check is in the mail, so... we'll see",
        "still no callback from the pharmacy about the refill",
        "gimme a bit, kid just woke up",
        "the surveyor's coming out next Tuesday, then we'll know more",
        "hol up loading",
        "waiting for my brother to wake up so we can leave",
        "I told the client I'd need another day to finalize the quote",
        "she's finishing her shift, said 6ish",
        "still pending, nothing new since this morning",
        "gimme a min the wifi's being weird",
        "waiting on my landlord to email back about the lease renewal",
        "he said he'd swing by this weekend to fix it",
        "brb, elevator's here",
        "hasn't shipped yet, tracking still says label created",
        "waiting to hear if the flight got rebooked",
        "one sec, letting the dog out",
        "still tryna track down that email, give me a sec",
        "she'll ping you the second she's off her call",
        "waiting on my roommate to Venmo me back, no rush tho",
        "the garage said theyd call once they know what's wrong",
        "gimme til after dinner, kinda slammed rn",
        "hol on charging my phone its at 1%",
        "still waiting on the contractor's quote, said end of week",
        "he's in a meeting, ill have him call after",
        "just sitting here waiting for the kettle lol",
        "no news yet on the job, they said two weeks",
        "give it another minute, still buffering",
        "waiting to hear back from three other places before I decide",
        "she said shed text once she's parked",
        "still on hold, 45 min in smh",
        "he's grabbing gas then he'll be right over",
        "the report's still with the auditor, should be back soon",
        "one sec letting this load",
        "waiting on my card to arrive in the mail",
        "still gotta hear back from three references before we can offer him the job",
        "gimme a sec my hands are full",
        "she's finishing up a call, said not long",
        "no word yet from the insurance adjuster",
        "brb train's coming"
    )

    // ---- REPLY (90) ----------------------------------------------------------------------

    private val replyTexts = listOf(
        "u up?",
        "So? What'd they say?",
        "Any thoughts on the venue?",
        "hello???",
        "How'd the interview go?",
        "Did you end up talking to him about it?",
        "k but fr, are we still doing this",
        "Just wondering if you got my last message",
        "hey stranger, long time no talk. how's life?",
        "Well? Don't leave me hanging",
        "did the package ever show up",
        "yo u good? haven't heard from u in days",
        "So what's the verdict on dinner",
        "Circling back on this — any update?",
        "u there",
        "How did it go with the landlord",
        "hows the new job treating u",
        "Just checking — are we still on for tomorrow?",
        "did u talk to her yet",
        "quick one — u free this weekend?",
        "so...?",
        "Any luck finding a sitter?",
        "u still mad at me",
        "How was the flight",
        "did that ever get sorted out",
        "hey, everything okay? you've been quiet",
        "Well, what did the doctor say?",
        "u coming or not",
        "so how'd it go with the bank",
        "just curious if you decided on the apartment",
        "hru",
        "Any word from the school yet?",
        "did he ever call you back",
        "so what's the plan then",
        "hows the diet going lol",
        "u free rn",
        "How'd your presentation go today?",
        "did the plumber ever show",
        "so are we good or",
        "Any news on the puppy?",
        "hey u alive over there",
        "How's your mom doing",
        "did u end up going with the blue one",
        "so what happened with the car",
        "u still there?? it's been like an hour",
        "How's the new place working out",
        "any update on the loan",
        "did she text you back",
        "so, are you coming to the thing or not",
        "hows it going with the new roommate",
        "u there? i sent that like 3 times now",
        "How was your day off",
        "did the results come back yet",
        "so what'd he say when u told him",
        "any thoughts, or are we all just gonna ignore this",
        "hey did u see what i sent",
        "How'd the audition go??",
        "did the check clear",
        "so we still on for saturday or nah",
        "u okay? that text seemed off",
        "How's the recovery going",
        "any word on the refund",
        "did u figure out what was wrong with it",
        "so, thoughts? be honest",
        "hey, u make it home okay?",
        "How's your sister settling in",
        "did u hear back from the other place",
        "so are we splitting the bill or",
        "u still up for tomorrow",
        "How was the move",
        "did he apologize or nah",
        "so what's next then",
        "hey haven't heard from u since friday, everything good?",
        "How's the tooth feeling",
        "did u end up telling them",
        "so, are you two okay now",
        "u good on gas or need me to swing by",
        "How'd the meeting with your boss go",
        "did the numbers add up",
        "so what did the vet say",
        "hey, did that email ever come through",
        "How's the ankle",
        "did u ask him about the raise",
        "so, we still doing thanksgiving at yours",
        "u there? getting worried",
        "How was meeting the parents",
        "did the offer come through yet",
        "so how'd the exam go",
        "hey u okay to drive tonight or should i come get u",
        "How's the new schedule treating u"
    )

    // ---- ACTION (90) ---------------------------------------------------------------------

    private val actionTexts = listOf(
        "grab milk on your way home",
        "Please have the deck ready before the 9am call.",
        "text the group chat the address",
        "Can you swing by the pharmacy before it closes?",
        "flip the breaker in the garage, it tripped again",
        "Kindly return the signed waiver to the front office by Friday.",
        "someone needs to walk the dog, i did it yesterday",
        "Please loop in finance on this thread.",
        "turn the oven off i forgot",
        "Could you proofread this before I send it to the client?",
        "drop the kids off at 7:45 sharp tmrw",
        "Please escalate this to the on-call engineer.",
        "someone move their car, it's blocking the driveway",
        "Can you grab an extra chair for the meeting?",
        "renew the car registration before it expires",
        "Please have the vendor resend the corrected invoice.",
        "unplug the space heater before u leave",
        "Can somebody take notes for the ones who missed the call?",
        "feed the fish, i forgot this morning",
        "Please forward the contract once legal signs off.",
        "grab extra napkins on ur way back",
        "Could you double check the flight times before booking?",
        "someone needs to reply to the Yelp review",
        "Please make sure the AC is off before locking up.",
        "text me the wifi password again",
        "Can you push the deploy after the meeting, not before?",
        "put the trash out tonight, pickup's early",
        "Please have HR update the org chart.",
        "someone grab the mail, it's been piling up",
        "Could you cc me on that email chain?",
        "check the oil before the road trip",
        "Please submit your timesheet by end of day.",
        "somebody needs to call the vet about the appointment",
        "Can you get the projector set up before everyone arrives?",
        "lock the back gate, the dog got out last time",
        "Please have the intern shadow the onboarding call.",
        "grab the charger from my desk if you're going that way",
        "Could you flag any typos in the draft?",
        "someone needs to defrost the chicken for dinner",
        "Please loop back with the client before Thursday.",
        "swap the batteries in the smoke detector, it's beeping",
        "Can you print two copies of the agenda?",
        "cancel the reservation if we're not going",
        "Please confirm the shipping address before we ship it out.",
        "someone water the plants while im away",
        "Could you check if the invoice went through?",
        "top off the tank before you return the rental",
        "Please have someone cover the front desk during lunch.",
        "grab a jacket, it's colder than it looks",
        "Can you resend that file, the link's broken",
        "someone needs to reset the router, wifi's been down",
        "Please make sure the contractor has building access tomorrow.",
        "return the library books, they're overdue",
        "Could you get a quote from a second vendor?",
        "somebody needs to sign for the package if I'm not home",
        "Please have the report translated before the board meeting.",
        "turn off the sprinklers, it rained already",
        "Can you send over your availability for next week?",
        "grab the folder off the printer, don't leave it there",
        "Please make sure everyone's badge is deactivated on their last day.",
        "someone needs to restock the coffee, we're out",
        "Could you check the smoke alarm batteries this weekend?",
        "cancel the gym membership before it auto-renews",
        "Please have the draft ready before I land.",
        "grab a cart, we're gonna need it",
        "Can somebody update the shared calendar?",
        "someone move the recycling bins back after pickup",
        "Please confirm attendance for the retreat by Monday.",
        "swap my shift with someone if you can",
        "Could you check the tire pressure before the trip?",
        "somebody needs to email the caterer about the headcount",
        "Please have security clear the visitor list.",
        "grab extra hangers from the closet upstairs",
        "Can you get this notarized before Friday?",
        "someone needs to close the pool cover, storm's coming",
        "Please make sure the backup generator is fueled.",
        "return the drill to the neighbor, we're done with it",
        "Could you get everyone's dietary restrictions before the dinner?",
        "grab the spare key from under the mat",
        "Please have the new hire's laptop set up before Monday.",
        "someone needs to unstick the printer, it's jammed again",
        "Can you check if the domain renewal went through?",
        "cancel tomorrow's meeting if he's still out sick",
        "Please make sure the fire extinguisher is up to code.",
        "grab a few extra chairs, more people RSVP'd",
        "Could you follow up with the landlord about the lease?",
        "someone needs to move the couch before the delivery guys come",
        "Please have the slides finalized before the rehearsal.",
        "swap the propane tank, it's empty",
        "Can you check if the refund actually posted?"
    )

    private fun sourceAppFor(text: String) =
        if (text.first().isUpperCase() && text.contains(Regex("\\bplease\\b", RegexOption.IGNORE_CASE))) GMAIL
        else if (text.length < 20) WHATSAPP
        else if (text.hashCode() % 3 == 0) SMS else WHATSAPP

    private fun build(texts: List<String>, expected: ClassifiedState, tiBase: Int): List<HCase> =
        texts.mapIndexed { i, text ->
            HCase(sourceAppFor(text), NAMES[i % NAMES.size], text, expected, tiBase + i, 0, false)
        }

    fun buildCorpus(): List<HCase> =
        build(waitingTexts, ClassifiedState.WAITING, 40000) +
            build(replyTexts, ClassifiedState.REPLY, 41000) +
            build(actionTexts, ClassifiedState.ACTION, 42000)
}
